const monsterSchema = {
  index: String,
  name: String,
  size: String,
  type: String,
  subtype: String,
  alignment: String,
  armor_class: String,
  hit_points: String,
  hit_dice: [],
  speed: Object,
  strength: Number,
  dexterity: Number,
  constitution: Number,
  intelligence: Number,
  wisdom: Number,
  charisma: Number,
  proficiencies: [Object],
  damage_vulnerabilities: [String],
  damage_resistances: [String],
  damage_immunities: [String],
  senses: Object,
  languages: String,
  challenge_rating: Number,
  xp: Number,
  special_abilities: [Object],
  actions: [Object],
  legendary_actions: [Object],
  url: String,
  status: Object,
  image: String,
  savingThrows: [String],
  skills: [String]
};
module.exports = monsterSchema;
